SELECT table_name FROM user_tables
DROP TABLE UTILISATEUR CASCADE CONSTRAINTS
DROP TABLE PHOTO CASCADE CONSTRAINTS
DROP TABLE FICHIERIMG CASCADE CONSTRAINTS
DROP TABLE CODEUNIVERSEL CASCADE CONSTRAINTS
DROP TABLE CODEPROMO CASCADE CONSTRAINTS
DROP TABLE CODEPERSONNEL CASCADE CONSTRAINTS
DROP TABLE CATALOGUE CASCADE CONSTRAINTS
DROP TABLE ADRESSE CASCADE CONSTRAINTS
DROP TABLE COMMANDE CASCADE CONSTRAINTS
DROP TABLE UTILISATIONCODEUTILISATEUR CASCADE CONSTRAINTS
DROP TABLE TIRAGE CASCADE CONSTRAINTS
DROP TABLE IMPRESSION CASCADE CONSTRAINTS
DROP TABLE GARDIENS CASCADE CONSTRAINTS
DROP TABLE CALENDRIER CASCADE CONSTRAINTS
DROP TABLE CADRE CASCADE CONSTRAINTS
DROP TABLE ARTICLE CASCADE CONSTRAINTS
DROP TABLE ALBUM CASCADE CONSTRAINTS
DROP TABLE AGENDA CASCADE CONSTRAINTS
SELECT table_name FROM user_tables
